/* eslint-disable */

// @ts-nocheck

// Autogenerated file. Do not edit.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => { return IDL.Service({}); };

export const init = ({ IDL }) => { return []; };